### ISSUE TITLE
Integration with a database/ORM

### ISSUE THREAD

**Issue by NoahTheDuke** [stefanvermaas/factory-builder#28]
This looks like a very cool project. One thing I'd love to see is an easy way to integrate with an ORM to allow for persisting built objects. Given that I might wish to test a function that makes a call to the database, it would be helpful to have either a helper function inside `factory-builder` or a tutorial on how to persist the objects "built" with `factory-builder`.

**Comment by stefanvermaas** [comment]
Thanks @NoahTheDuke!

I'm unsure why (and how) I ever missed this issue, but you're right. It would be nice to be able to use it with an ORM. After my holiday I'll look into how we could make this work.

**Comment by Gibzon69** [comment]
This is pretty straight forward to do. I'm using Sequelize and using it like this:

`afterBuild: async (attributes) => global.db.order.create(attributes),`

Example in the test:
`const order = await build(Order)`
Or with buildList:
`const orders = await Promise.all(buildList(Order, 2))`

In my Jest setup file I have set global.db to the sequelize instance.

**Comment by stefanvermaas** [comment]
Hi @Gibzon69! That sounds like a solid way - for now - to support persistence. Would you mind opening a PR to add documentation for this?

**Comment by Gibzon69** [comment]
> Hi @Gibzon69! That sounds like a solid way - for now - to support persistence. Would you mind opening a PR to add documentation for this?

Sure, I can do that.
Since I have the other PR in main branch on my forked repo. How would I go about doing this PR that should probably be based on your main branch. Do I have to create a completely new fork?

**Comment by stefanvermaas** [comment]
Hi @Gibzon69, sorry for the insanely late response. I thought I already responded to this as it was out of my notifications 🤦‍♂️ ! 

You can update your fork through Github. Click the "Fetch Upstream" and choose "Fetch and Merge". Now, your fork is up-to-date and you can make your changes.

<img width="941" alt="Screenshot 2022-01-25 at 10 14 24" src="https://user-images.githubusercontent.com/1470863/151003900-d2b47bb5-dba2-4f70-a431-a340f091c50e.png">

When you're ready, use the "Contribute" button on Github and click "Open a pull request". Let me know if there's anything else I can do to help. 

My sincere apologies for the extremely late response 🙇

**Comment by Gibzon69** [comment]
Hi @stefanvermaas 
No problem :)
Thanks for the info on how to do this. I have now created a pull request. Feel free to change any text or the example itself.

**Comment by stefanvermaas** [comment]
It's perfect! Merged it!
