### ISSUE TITLE
Example usage of afterBuild in the buildList call

### ISSUE THREAD

**Issue by humbienri** [stefanvermaas/factory-builder#292]
Hello,
I've been wracking my brain at this for a while. I've even searched through your tests code and the Issues list but I can't figure it out.

In your documentation regarding `beforeBuild` and `afterBuild`, you say:
"These methods can be globally defined on your factory or can be passed to the build method."
but I cannot for the life of me get it to work. Some help please?

I basically need to return an array of objects but with an added top level key. Example
```{
listings: [
{
id: 3,
title: some job description 1
},
{
id: 3,
title: some job description 1
},
{
id: 3,
title: some job description 1
}
]
}
```
Each one of the objects inside the array I can get by defining a Job Factory for. And using the `buildList` API I can get an array of them. But I can't seem to figure out how to insert that top level `listings' key.

This is what I have so far:
```
const aJob = buildList(Job, 3, { search_id: 13 }, {beforeBuild: (attributes) => {
  return {
    ...attributes,
    platoon: `${attributes.location}s`
  }
}});
console.log(aJob);
```

In advance, thank you!

**Comment by stefanvermaas** [comment]
Hi @humbienri! Thanks for trying factory-builder. The `beforeBuild` should be defined on the factory itself. You can't pass the `beforeBuild` callback to the `buildList` method.

I hope this example makes sense to you.

```javascript
const Job = {
  attributes: {
    id: 1,
    title: 'Some Job Description',
  },

  beforeBuild: (attributes) => {
    return {
      ...attributes,
      platoon: `${attributes.location}s`
    };
  }
}

const jobs = buildList(Job, 3, { search_id: 13 });
```

**Comment by humbienri** [comment]
Hi @stefanvermaas! Thank you for the response. So am I misreading or misunderstanding your documentation? The part about "passing it to the build method?

I did try the approach of actually declaring it in the Factory declaration itself but that wasn't giving me quite the results I am looking for. Namely the json object structure listed above.

Thanks again sir.

**Comment by stefanvermaas** [comment]
Hmm, I believe you're right. You didn't misunderstand the documentation. It's a bug indeed. I'll do some testing on the `build` and `buildList` methods and report back.

**Comment by stefanvermaas** [comment]
Hi @humbienri, I was finally able to take a look at it. It has been a while since I created this package, so I had to refresh my memory a bit.

It seems that the documentation wasn't entirely clear after all. It's not possible to pass the `beforeBuild` or `afterBuild` as extra attributes. Instead, one should add the `beforeBuild` and/or `afterBuild` to the Factory itself.

```javascript
// ./factories/User.js
const Job = {
  attributes: {
    title: 'Some job description',
  },

  beforeBuild: (attributes) => {
    return {
      ...attributes,
      platoon: `${attributes.location}s`
    };
  }
};

export default User;
```

See the updated documentation here: https://github.com/stefanvermaas/factory-builder#before-and-after-hooks. 

I hope this helps.

**Comment by stefanvermaas** [comment]
Also see this issue: https://github.com/stefanvermaas/factory-builder/issues/14. I believe it exactly describes what you want. However, I haven't had the time to implement it. Just like I haven't had the time to implement the sequencing strategy yet.
